version: '3'

services:
  db:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./db/mysql_data:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: 'nestjs-prisma-test'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
